### ISSUE TITLE
ETA for grayscale/color JPEG compression artifact reduction model release?

### ISSUE THREAD

**Issue by AIisCool** [mv-lab/swin2sr#1]
Very impressive so far with the SR results! The artifact reduction results shown here and in the paper look very promising. Wondering if there was an ETA on when they'd be available?

**Comment by mv-lab** [comment]
@AIisCool ETA for the model and qualitative samples is today/tomorrow :)  stay tuned please
you can have a look at the demo here https://www.kaggle.com/code/jinssaa/swin2sr-dev/notebook we are also preparing a collab and replicate demo.
If you need something else, please email us.

**Comment by AIisCool** [comment]
@mv-lab fantastic I didn't expect it to be so soon! Quick additional question: Is it possible to test the compression artifact reduction on images where I don't have a HR groundtruth image, so similar to the RealSR model which doesn't need a gt folder?

Also just tested it where I did have a HR groundtruth image and received:

`File "C:\swin2sr\main_test_swin2sr.py", line 289, in <module>
    main()
  File "C:\swin2sr\main_test_swin2sr.py", line 116, in main
    if img_gt is not None:
UnboundLocalError: local variable 'img_gt' referenced before assignment`

**Comment by Choiuijin1125** [comment]
@AIisCool I Added `save_img_only` flag in #2  you can try this to save image only :)
We will review first and merge this function sometime soon.

FYI

`File "C:\swin2sr\main_test_swin2sr.py", line 289, in <module> main() File "C:\swin2sr\main_test_swin2sr.py", line 116, in main if img_gt is not None: UnboundLocalError: local variable 'img_gt' referenced before assignment`

This error happen when gt folder is not founded. Can you share your full command?
