### ISSUE TITLE
A small question?

### ISSUE THREAD

**Issue by CrissyHoo** [mv-lab/swin2sr#10]
in Jpeg compression, the used window size is 7, what if the input image size cannot totally be divided by 7? then some code like 
x=x.view(...) will produce bug.

**Comment by mv-lab** [comment]
@CrissyHoo  I do not remember the details but probably padding is being applied

**Comment by CrissyHoo** [comment]
> @CrissyHoo I do not remember the details but probably padding is being applied

I noticed that in test function there is a param named tile. if we don't use tile, then the lq is tested as a whole. Does that mean if the image size can be divided by window size, then we can choose not to use tile. Or we have to use tile?
