### ISSUE TITLE
Compatibility with Automatic1111/Automatic

### ISSUE THREAD

**Issue by Woisek** [mv-lab/swin2sr#15]
Found this great model and wantetd to know, if there is a plan to make it more comaptible to repos like https://github.com/AUTOMATIC1111/stable-diffusion-webui / https://github.com/vladmandic/automatic to be used ... ?
Right now, it throws an error when doing so. Maybe some small alteration could help?

Thanks in advance.

**Comment by mv-lab** [comment]
@Woisek Swin2SR is integrated into [https://github.com/AUTOMATIC1111/stable-diffusion-webu](https://github.com/AUTOMATIC1111/stable-diffusion-webui)

check this PR https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/2092

**Comment by Woisek** [comment]
Cool! Will test it, thanks!
