### ISSUE TITLE
How can I train my data set with your pre-training model

### ISSUE THREAD

**Issue by Bugs-Bunny01** [mv-lab/swin2sr#20]
Hi.How can I train my data set with your pre-training model

**Comment by 1632325673** [comment]
训练代码我怎么没有找到

**Comment by 1632325673** [comment]
The training code is at [KAIR](https://github.com/cszn/KAIR/). We follow the same training setup as [SwinIR](https://github.com/JingyunLiang/SwinIR/) by [Jingyun Liang](https://jingyunliang.github.io/). We are working on KAIR integration 👀 More details about the training setup in our [paper](https://arxiv.org/abs/2209.11345).怎么没找到Swin2SR的训练代码
