### ISSUE TITLE
The output look cartoonish

### ISSUE THREAD

**Issue by deepakkupanda** [mv-lab/swin2sr#4]
I am trying the output of swin2sr for super-resolution.
https://huggingface.co/spaces/jjourney1125/swin2sr
<img width="776" alt="image" src="https://user-images.githubusercontent.com/41481181/195093101-349a74a6-baa7-423a-9583-359ebd88cbc0.png">
The output looks cartoonish. 
Is there any other way by which I can reduce the cartoonish effect.

**Comment by mv-lab** [comment]
hey @deepakkupanda thanks for pointing out. We were playing with different model checkpoints and there was a bug, the model loaded in the app was wrong. **Now it is fixed** as you can check https://github.com/mv-lab/swin2sr:

![Screenshot from 2022-10-11 16-23-23](https://user-images.githubusercontent.com/37480508/195118195-0abb428b-eb30-4766-995c-4abdb3e56a37.png)

Note that as we mention in the demo: `This Demo expects low-quality and low-resolution JPEG compressed images, in the near future we will support any kind of input` We are working on this and we will allow to select different models. Hopefully we will finish those tweaks soon

thanks for you feedback :)
